### ISSUE TITLE
[terra-clinical-detail-view]+[terra-clinical-label-value-view] Update Secondary Text Color

### ISSUE THREAD

**Issue by neilpfeiffer** [cerner/terra-clinical#691]
# Feature Request

## Description

The Label color in the Label-Value-View (also used in the Detail-View) was still set to use solid hex color instead of an RGBA, similar to how we've updated it other Terra components. 

## Instructions:
Items needing to be updated:

- [ ] 1. Change default theme color from `#75767d` to `rgba(28, 31, 33, 0.65)` 
https://github.com/cerner/terra-clinical/blob/5178c39511491f49b910a1df35df3b15fdc05466/packages/terra-clinical-label-value-view/src/LabelValueView.module.scss#L15

- [ ] 2. Change the Fusion theme color from `#6f7477` to `rgba(28, 35, 40, 0.73)`
https://github.com/cerner/terra-clinical/blob/5178c39511491f49b910a1df35df3b15fdc05466/packages/terra-clinical-label-value-view/src/orion-fusion-theme/LabelValueView.module.scss#L3

- [ ] 3. Change the Lowlight theme color from `#6f7477` to `rgba(221, 224, 225, 0.41)`
https://github.com/cerner/terra-clinical/blob/5178c39511491f49b910a1df35df3b15fdc05466/packages/terra-clinical-label-value-view/src/clinical-lowlight-theme/LabelValueView.module.scss#L3

- [ ] 4. Update wdio snapshots and changelogs for both Clinical-Label-Value-View and Clinical-Detail-View
